# Generated by Django 4.2.5 on 2024-11-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_alter_employee_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
