# Generated by Django 4.2.5 on 2024-11-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_remove_employee_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
